[package]
name = "rime_wanxiang_updater"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "6.0.0"
rust-embed = { version = "8.7.2", features = ["compression"] }
single-instance = "0.3.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
